'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class WideWorldImportersEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=WideWorldImportersEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Customers() As DbSet(Of Customer)

    Public Overridable Function GetCityUpdates(lastCutoff As Nullable(Of Date), newCutoff As Nullable(Of Date)) As Integer
        Dim lastCutoffParameter As ObjectParameter = If(lastCutoff.HasValue, New ObjectParameter("LastCutoff", lastCutoff), New ObjectParameter("LastCutoff", GetType(Date)))

        Dim newCutoffParameter As ObjectParameter = If(newCutoff.HasValue, New ObjectParameter("NewCutoff", newCutoff), New ObjectParameter("NewCutoff", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("GetCityUpdates", lastCutoffParameter, newCutoffParameter)
    End Function

    Public Overridable Function GetCustomerUpdates(lastCutoff As Nullable(Of Date), newCutoff As Nullable(Of Date)) As Integer
        Dim lastCutoffParameter As ObjectParameter = If(lastCutoff.HasValue, New ObjectParameter("LastCutoff", lastCutoff), New ObjectParameter("LastCutoff", GetType(Date)))

        Dim newCutoffParameter As ObjectParameter = If(newCutoff.HasValue, New ObjectParameter("NewCutoff", newCutoff), New ObjectParameter("NewCutoff", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("GetCustomerUpdates", lastCutoffParameter, newCutoffParameter)
    End Function

    Public Overridable Function GetEmployeeUpdates(lastCutoff As Nullable(Of Date), newCutoff As Nullable(Of Date)) As Integer
        Dim lastCutoffParameter As ObjectParameter = If(lastCutoff.HasValue, New ObjectParameter("LastCutoff", lastCutoff), New ObjectParameter("LastCutoff", GetType(Date)))

        Dim newCutoffParameter As ObjectParameter = If(newCutoff.HasValue, New ObjectParameter("NewCutoff", newCutoff), New ObjectParameter("NewCutoff", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("GetEmployeeUpdates", lastCutoffParameter, newCutoffParameter)
    End Function

End Class
